"""Build the secondary Figure 1 robustness result from newer public data.

This entry point never reads the authors' replication kit.  The primary
authors-kit reconstruction has a separate entry point in
``build_figure1_authors_data.py`` and writes to different output paths.
"""

from pathlib import Path

import pandas as pd

from unveiling import (
    build_figure1_series,
    plot_figure1,
    read_fred_national_income,
    read_fwtw,
)


PROJECT_ROOT = Path(__file__).resolve().parents[2]
FWTW_PATH = PROJECT_ROOT / "Data/raw/fwtw/fwtw_data_2026-06-18.csv"
NATIONAL_INCOME_PATH = (
    PROJECT_ROOT
    / "Data/raw/national_income/A032RC1A027NBEA_2026-08-05.csv"
)
SERIES_PATH = (
    PROJECT_ROOT
    / "Data/processed/figure1_indirect_household_ownership.csv"
)
FIGURE_PATH = (
    PROJECT_ROOT
    / "Results_Proposal/figures/figure1_indirect_household_ownership.png"
)
VALUES_PATH = PROJECT_ROOT / "Presentation/generated/figure1_values.tex"


def main() -> None:
    """Read pinned inputs, build the annual series, and export the figure."""

    fwtw = read_fwtw(FWTW_PATH)
    national_income = read_fred_national_income(NATIONAL_INCOME_PATH)
    series = build_figure1_series(fwtw, national_income)

    SERIES_PATH.parent.mkdir(parents=True, exist_ok=True)
    series.to_csv(SERIES_PATH, index=False)
    plot_figure1(series, FIGURE_PATH)
    _write_latex_values(series, VALUES_PATH)

    peak = series.loc[series["indirect_share"].idxmax()]
    print("Approach: secondary newer-public-data robustness")
    print(f"Wrote {SERIES_PATH.relative_to(PROJECT_ROOT)}")
    print(f"Wrote {FIGURE_PATH.relative_to(PROJECT_ROOT)}")
    print(f"Wrote {VALUES_PATH.relative_to(PROJECT_ROOT)}")
    print(
        "Anchors: "
        f"1963 share={series.iloc[0]['indirect_share']:.3f}, "
        f"peak={peak['indirect_share']:.3f} in {int(peak['year'])}, "
        f"2019 share={series.iloc[-1]['indirect_share']:.3f}"
    )


def _write_latex_values(series: pd.DataFrame, path: Path) -> None:
    """Write the small set of generated values used in the deck and report."""

    indexed = series.set_index("year")
    start = series.iloc[0]
    end = series.iloc[-1]
    peak = series.loc[series["indirect_share"].idxmax()]
    commands = {
        "FigureOneStartYear": str(int(start["year"])),
        "FigureOneStartShare": _latex_percent(start["indirect_share"]),
        "FigureOneStartLevel": _latex_percent(
            start["indirect_assets_to_national_income"]
        ),
        "FigureOneSevenShare": _latex_percent(
            indexed.loc[2007, "indirect_share"]
        ),
        "FigureOneSevenLevel": _latex_percent(
            indexed.loc[2007, "indirect_assets_to_national_income"]
        ),
        "FigureOnePeakYear": str(int(peak["year"])),
        "FigureOnePeakShare": _latex_percent(peak["indirect_share"]),
        "FigureOneEndShare": _latex_percent(end["indirect_share"]),
        "FigureOneEndLevel": _latex_percent(
            end["indirect_assets_to_national_income"]
        ),
    }
    lines = [
        "% Generated by Code/scripts/build_figure1.py. Do not edit.",
        *(f"\\newcommand{{\\{name}}}{{{value}}}" for name, value in commands.items()),
        "",
    ]
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text("\n".join(lines), encoding="utf-8")


def _latex_percent(value: float) -> str:
    """Format a fraction as a one-decimal LaTeX percentage."""

    return f"{value:.1%}".replace("%", r"\%")


if __name__ == "__main__":
    main()
