"""Generate numerical LaTeX inputs for the unveiling teaching presentation."""

from pathlib import Path

import numpy as np

from unveiling import DirectOwnershipNetwork


PROJECT_ROOT = Path(__file__).resolve().parents[2]
OUTPUT_PATH = PROJECT_ROOT / "Presentation" / "generated" / "unveiling_values.tex"


def _latex_matrix(matrix: np.ndarray, decimals: int = 5) -> str:
    """Format a small numeric array as a LaTeX ``bmatrix`` body."""

    rows = [
        " & ".join(f"{value:.{decimals}f}" for value in row)
        for row in matrix
    ]
    return r" \\ ".join(rows)


def _latex_percentage(value: float, decimals: int = 2) -> str:
    """Format a unit share as a LaTeX percentage."""

    return f"{100 * value:.{decimals}f}\\%"


def main() -> None:
    """Compute the worked example and write stable Beamer macros."""

    direct_ownership = np.array(
        [
            [1.0, 0.0, 0.0, 0.0],
            [0.0, 1.0, 0.0, 0.0],
            [0.2, 0.1, 0.0, 0.7],
            [0.6, 0.2, 0.2, 0.0],
        ]
    )
    network = DirectOwnershipNetwork(direct_ownership, n_owners=2)
    omega = network.unveiled_ownership()
    b_matrix = direct_ownership[2:, :2]
    q_matrix = direct_ownership[2:, 2:]

    bank_direct_household = b_matrix[0, 0]
    bank_via_fund_household = q_matrix[0, 1] * omega[1, 0]
    bank_loop_factor = q_matrix[0, 1] * q_matrix[1, 0]
    bank_fixed_point_base = (
        bank_direct_household + q_matrix[0, 1] * b_matrix[1, 0]
    )

    q_power = np.eye(q_matrix.shape[0])
    bank_household_path_terms = []
    for _ in range(6):
        bank_household_path_terms.append((q_power @ b_matrix)[0, 0])
        q_power = q_power @ q_matrix
    path_series = " + ".join(
        _latex_percentage(value, decimals=3)
        for value in bank_household_path_terms
    )
    path_preview = " + ".join(
        _latex_percentage(value, decimals=3)
        for value in bank_household_path_terms[:4]
    )

    intermediation = network.intermediation_matrix()
    term = intermediation.copy()
    seven_round_sum = np.zeros_like(intermediation)
    for _ in range(7):
        seven_round_sum += term
        term = term @ intermediation
    seven_round_omega = seven_round_sum[2:, :2]
    max_seven_round_gap = np.max(np.abs(omega - seven_round_omega))

    content = (
        "% Generated by Code/scripts/build_unveiling_teaching_assets.py.\n"
        "% Do not edit numerical values by hand.\n"
        f"\\newcommand{{\\ToyDirectOwnershipBody}}"
        f"{{{_latex_matrix(direct_ownership, 1)}}}\n"
        f"\\newcommand{{\\ToyBBody}}{{{_latex_matrix(b_matrix, 1)}}}\n"
        f"\\newcommand{{\\ToyQBody}}{{{_latex_matrix(q_matrix, 1)}}}\n"
        f"\\newcommand{{\\ToyOmegaBody}}{{{_latex_matrix(omega)}}}\n"
        f"\\newcommand{{\\ToySevenRoundBody}}{{{_latex_matrix(seven_round_omega)}}}\n"
        f"\\newcommand{{\\ToyBankDirectHousehold}}"
        f"{{{_latex_percentage(bank_direct_household, 0)}}}\n"
        f"\\newcommand{{\\ToyFundUltimateHousehold}}"
        f"{{{_latex_percentage(omega[1, 0], 3)}}}\n"
        f"\\newcommand{{\\ToyBankViaFundHousehold}}"
        f"{{{_latex_percentage(bank_via_fund_household, 3)}}}\n"
        f"\\newcommand{{\\ToyBankUltimateHousehold}}"
        f"{{{_latex_percentage(omega[0, 0], 3)}}}\n"
        f"\\newcommand{{\\ToyBankFixedPointBase}}"
        f"{{{_latex_percentage(bank_fixed_point_base, 0)}}}\n"
        f"\\newcommand{{\\ToyBankLoopFactor}}"
        f"{{{_latex_percentage(bank_loop_factor, 0)}}}\n"
        f"\\newcommand{{\\ToyBankHouseholdPathSeries}}"
        f"{{{path_series} + \\cdots}}\n"
        f"\\newcommand{{\\ToyBankHouseholdPathPreview}}"
        f"{{{path_preview} + \\cdots}}\n"
        f"\\newcommand{{\\ToyMaxSevenRoundGap}}"
        f"{{{max_seven_round_gap:.5f}}}\n"
        f"\\newcommand{{\\ToyMaxSevenRoundGapPP}}"
        f"{{{100 * max_seven_round_gap:.3f}}}\n"
    )

    OUTPUT_PATH.parent.mkdir(parents=True, exist_ok=True)
    OUTPUT_PATH.write_text(content, encoding="utf-8")
    print(OUTPUT_PATH.relative_to(PROJECT_ROOT))


if __name__ == "__main__":
    main()
